[app]
# 项目名称，由需求方决策
name = 'AppName'
# 项目版本，与需求方同步
version = '0.0.0'

[service]

  # 生产环境和测试环境的
  [service.hosts]
  dev = '127.0.0.1'
  prod = 'your.api.domain'


[cdn]
cdn_host = '127.0.0.1'
cdn_port = '8080'
cdn_key  = 'Your cdn key'

[PWA]
# 是否启用 PWA
enable = false
